### ISSUE TITLE
[BUG] /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found

### ISSUE THREAD

**Issue by JameWade** [dojoengine/dojo#1203]
**Describe the bug**
when i install dojo,i find this err,and i try to reinstall libc6,but the system was destroyed.I checked my libc, the version is 2.31.But I can't upgrade it correctly

**To Reproduce**
dojoup

**Expected behavior**
Make a wider range of adaptation

**Screenshots**
![image](https://github.com/dojoengine/dojo/assets/47301518/7175e511-45fe-43d2-a5b5-185bc0516cef)
![image](https://github.com/dojoengine/dojo/assets/47301518/b5222b4a-da4a-41cb-ba37-f8289693a072)

**Additional context**
ubuntu 20.04

**Comment by ponderingdemocritus** [comment]
What ubuntu version are you on?

**Comment by lambda-0x** [comment]
this happens because rust dynamically links with the glibc version in the machine that is used to compile the release binary (`ubuntu-latest` in CI which uses glibc version 2.32) and [glibc version are not backward compatible](https://stackoverflow.com/questions/11107263/how-compatible-are-different-versions-of-glibc).

So here we have two options:
- use LTS version of ubuntu to compile release binaries
- provide musl binaries along with glibc ones for people who may need it

**Comment by lambda-0x** [comment]
@JameWade try using the binary from latest release, issue should have been fixed.

https://github.com/dojoengine/dojo/releases/tag/v0.4.4

**Comment by glihm** [comment]
Will close this one after running tests on some VMs to ensure compatibility.
Thank you @lambda-0x for the fix, @JameWade please feel free to open a new one if something else happens on your side. :+1:
