### ISSUE TITLE
Tx failing silently when failing to commit db tx

### ISSUE THREAD

**Issue by notV4l** [dojoengine/dojo#1650]
**Describe the bug**
When katana is out of space for db, this error occurs : 
`ERROR node: failed to mine block: failed to commit db transaction: Input/output error`

It seems the tx fails silently & waitForTransaction timeout

There might be a similar issue with other DatabaseError.s

**Expected behavior**
tx should be rejected with useful error msg

**Comment by kariy** [comment]
I don't think the expected behaviour is correct. This is an issue that is beyond the scope of the RPC specs, and the rejected status is not meant to describe unexpected cases like this, as this issue is completely unrelated to the tx itself.

One way I could think of to handle hardware issues like this, is to retry the mining process again, instead of just dropping the block when it failed to mine.
