### ISSUE TITLE
[torii] exact starting block number

### ISSUE THREAD

**Issue by notV4l** [dojoengine/dojo#2014]
**Describe the bug**
If the exact block number of world deployment is provided, torii will fail with 
`ERROR tori_core::engine: Syncing to head. error=no rows returned by a query that expected to return at least one row`

**Expected behavior**
The starting provided block should be indexed

**Additional context**
alpha-3

**Comment by Larkooo** [comment]
After investigation, --start-block doens't seem to be behaving incorrectly. On sepolia it does seem to resume at the correct block number from my tests and I believe the issue might be linked to something else; 

The only time where the torii engine can panic because of a "no rows returned by a query" is when trying to fetch a model, which happens when an entity gets updated (store_set_record). So in my opinion, the starting block number was set to be after the world emitted the ModelRegistered events and thus, the store_set_record processors failed due to torii not catching those initial events
