### ISSUE TITLE
[core] when migrating world address overrides cli address

### ISSUE THREAD

**Issue by ponderingdemocritus** [dojoengine/dojo#2066]
**Current behaviour**

If the world address is listed in `scarb.toml` then passing in a new `name` doesn't do anything, and the world will migrate to the existing address in `scarb.toml`

`sozo --profile prod migrate apply --name eternum1`

**Expected behaviour**
An error should be thrown in the above cli command if a world address doesn't match the name.

**Comment by glihm** [comment]
Good report, we've discussed that with @lambda-0x recently, it's due to the fact that if a world address is provided, it takes precedence on the name usage to compute the deterministic address.

We've a rework in mind, but we need to take in account that when you provide a name, it's not enough to be deterministic. Because if the dojo version has changed, the same name will produce a different address if original class hashes are not provided.

**Comment by glihm** [comment]
Linked to #2040.
