### ISSUE TITLE
Authorizations using overlays seem to fail

### ISSUE THREAD

**Issue by notV4l** [dojoengine/dojo#2079]
**Describe the bug**
For some reason i had this error first time i deployed my world : 

```
[all prev auth ok]
 > Authorizing rollyourown::systems::ryo::ryo for Models: ["RyoConfig", "RyoAddress", "Season", "SeasonSettings"]
 > Failed to auto authorize with error: Provider errror Other(TransportError(Json(Error("expected value", line: 2, column: 1)))).
 ```

I relaunched `sozo migrate apply` then it say 

` > Auto authorize completed successfully`

but seems its not the case.

We could have a new command `sozo auth apply`, setting auth from overlays

**Comment by glihm** [comment]
Do like the idea of `sozo auth apply` to ensure this can be re-run without actually doing the migration. Or we may have `sozo migrate apply` that always re-run auth independently if some contracts have been updated?

**Comment by glihm** [comment]
@notV4l did you experienced this again? If yes and if it's on Katana, would you have the sequencer error?

**Comment by lambda-0x** [comment]
issues: 
- since we depend on `MigrationOutput` from apply_diff to do `auth authorize` so if this operation
failed for any reason during rerun we won't run it again

- simiarly for ipfs metadata we upload when we have something in `MigrationOutput` so it suffers
the same problem

solutions:
- provide ability to force apply this value by a separate command line flag
- add a boolean flag for this in manifest which describes when this needs to run

**Comment by glihm** [comment]
Let's do the `2nd` option for now yeah. This should help to have a better behavior. 👍
