### ISSUE TITLE
`useEntityQuery` returns deleted entities

### ISSUE THREAD

**Issue by jainkunal** [dojoengine/dojo#2098]
**Describe the bug**
The entities returned from useEntityQuery also contained entities that have been deleted.

The following code is the snippet I use

```
const v = useEntityQuery([HasValue(Tile, { game_id: 1 })])
Object.values(v).map((tileId: any) => {
    return <TileComponent key={tileId} tileId={tileId} />;
})
```

// In TileComponent
```
useComponentValue(Tile, tileId)
```

**Expected behavior**
Deleted entities should not be return when using `useEntityQuery`

**Additional context**
Torii version: 0.7.2

**Comment by fishonamos** [comment]
Kindly assign  @jainkunal

**Comment by glihm** [comment]
@Larkooo would you have any insight on this one? Do you think it's at the DB level, because we recently merged a PR that actually ensured correct deletion iirc: #2071.

@fishonamos are you already familiar with the stack to tackle such issue? Do you have any hint of what could happen?

**Comment by Larkooo** [comment]
> @Larkooo would you have any insight on this one? Do you think it's at the DB level, because we recently merged a PR that actually ensured correct deletion iirc: #2071.
> 
> @fishonamos are you already familiar with the stack to tackle such issue? Do you have any hint of what could happen?

I don't think so. Deleted entities are correctly wiped off the DB. My insight is that the issue comes from the state management in dojo.JS. It does not know when entities get deleted, so doesn't get rid of them on the client storage. This issue is also susceptible to happen on unity. As for now, we do not have a RPC endpoint / way of telling the client that entities are deleted. They are only deleted on the torii DB.

**Comment by Larkooo** [comment]
@ponderingdemocritus

**Comment by Larkooo** [comment]
To add more precision, this could also be due to us still keeping a record of the entity in the `entities` table but all of its models data deleted. So if you query a deleted entity, that entity will have 0 models, which means it has been deleted. It's nice in the case you wanna know if an entity has just been created (or keep record of when it was initially created) or if it has been deleted, because a deletion doesn't actually delete the entity but just its models data. Thus, the entity is still returned from the fetch but with no models.  It might be something to think about though and I think that both solutions have their own pros and cons

**Comment by fishonamos** [comment]
Can we then filter out entities with 0 data when calling useEntityQuery?. Thus, only entities with models are returned.  Since entities themselves can't be deleted.
