### ISSUE TITLE
Remove patches from `Cargo.toml`

### ISSUE THREAD

**Issue by tcoratger** [dojoengine/dojo#2452]
Due to custom patches

https://github.com/dojoengine/dojo/blob/5777c0076576de369bba7fe9ffd73abe38447dd3/Cargo.toml#L248-L253

this is difficult to integrate Dojo as package due to dependency issues.

With the recent bump of `starknet` to 0.12 https://github.com/xJonathanLEI/starknet-rs/pull/655 maybe we could bump the dependency.

https://github.com/xJonathanLEI/starknet-rs/pull/657 should also be useful to remove all the patches as per this comment

https://github.com/dojoengine/dojo/blob/5777c0076576de369bba7fe9ffd73abe38447dd3/Cargo.toml#L242-L245

**Comment by kariy** [comment]
@tcoratger thanks! 

i had just taken look over our patches again, `starknet`'s patches can be fully removed now. i would need to update it on the other deps as well, but for `starknet-types-core` we might still need a patch. the patch can now be pointed to main repo https://github.com/starknet-io/types-rs/commit/245907a981b1d3361041df24af4d8e3d1326eab1 instead of our fork. let me try to ask the maintainer for a new patch release, so that we can remove the patch for it as well.

**Comment by tcoratger** [comment]
@kariy I think this https://github.com/cartridge-gg/cainome/pull/54 is also needed to remove all the patches.
