### ISSUE TITLE
bug: Felt252IntoU250

### ISSUE THREAD

**Issue by milancermak** [dojoengine/dojo#289]
felt252 into u250 should not be allowed because it might overflow. only try_into should be possible.

**Comment by aymericdelab** [comment]
i can take a look at this one

**Comment by aymericdelab** [comment]
@milancermak haven't finished yet but i'd love to have your opinion on this. atm I basically added the query try_into() implementations because now you need to try_into from felt252 to u250. Do you think it makes sense to have try_into query that accepts felt252 or would it be better to not do the impl for felt252 and just force to use only data types that can Into() u250 ?

**Comment by milancermak** [comment]
U250 literals would be 🔥 

The alternative is not to do anything and keep `Felt252IntoU250`.

I don't have a strong opinion on this. Curious what Tarrence or others have to say.

**Comment by aymericdelab** [comment]
might be wrong but my understanding is that the max that a `felt252` can represent is `P = 2^{251} + 17 * 2^{192}+1`. So that a felt252 would still have to be `try_into()` into a `u251`. The only thing that can be `into()` a felt252 would be `u252` and higher.
