### ISSUE TITLE
[Dojo] Compiler level packing

### ISSUE THREAD

**Issue by ponderingdemocritus** [dojoengine/dojo#532]
Storage is always going to be expensive. Volition will bring a massive cost reduction to state storage, but there will still be situations where volition will never make sense like ownership and tokens etc. If we wish to ship dojo worlds on mainnet soon we need to implement bit packing at the compiler level.

We should be able to effectively add a compiler plugin that creates the packing/unpacking functions according to a `Component` schema, which can then allow the component state to be packed in a single or multiple felts.

It might make sense to wait until the Cairo compiler is more stable idk.

Thoughts @milancermak @tarrencev @ftupas ?

**Comment by ftupas** [comment]
I think that's a great idea. Would it make sense to create like an attribute similar to `indexed: true` so like `packed: true`? And then the plugin handles the Component to generate the felt packing/unpacking 🙂 maybe just a question, how would the compiler know how many members can fit in a felt?

**Comment by milancermak** [comment]
Make sense and I agree this is something Dojo should do out of the box.

I think there are two approaches. One, as you suggested, is to derive the packing and unpacking functions only and let devs deal with storage. The second one is to derive our own `StorageAccess`, since the packing and unpacking should happen only when writing to or reading from storage.

IMO starting with 1) is better - it's smaller in scope and is a subset of 2), so we can do the `StorageAccess` afterwards.

> how would the compiler know how many members can fit in a felt?

That's a good question. We know it for primitive types (if I'm not mistaken, this is easy to get in the compiler plugin). Then we can start bolting on some optimizations - for example you have a member that you're absolutely certain will fit into say 3 bits, because there's no `u3` type, we could have support for annotating this struct member with sth like `#[pack(3)]` and the compiler would pick it up and you'd save 5 bits :) Then there's the question of ordering to get the most out of a felt (the compiler could to that as well I guess, but that needs work 😅 ).

**Comment by tarrencev** [comment]
This is definitely something we should support. I have an existing issue here for it: https://github.com/dojoengine/dojo/issues/386

Essentially, we need to move to a `dojo::StorageAccess` trait for reading/writing from storage. Once we do that, we can add a macro to derive the implementation automatically. The trait needs to expose the storage layout for schema introspection, so an indexer can parse it automatically.

As far as knowing how many members can fit in a felt, we would derive it for primitive types and any custom type on top of that would need all its members to support `dojo::StorageAccess` too

I think the steps here are:
1) Migrate to `dojo::StorageAccess` rather than the current serde
2) Derive naive `dojo::StorageAccess` (same as current serde)
3) Automatically calculate layout during compilation
4) Potentially allow more control of the layout using annotations
