### ISSUE TITLE
Support MUD interface in indexer

### ISSUE THREAD

**Issue by tarrencev** [dojoengine/dojo#79]
We can provide apis on the dojo indexer that conform to the mud spec here: https://mud.dev/packages/services/#services which will make dojo compatible with mud clients

**Comment by ludns** [comment]
I will ping here when new indexers are ready -- happy to help coordinate on this.

For MUD2, here is the what the indexer is looking for:
```
event StoreSetRecord(uint256 tableId, bytes32[] key, bytes data);
event StoreSetField(uint256 tableId, bytes32[] key, uint8 schemaIndex, bytes data);
event StoreDeleteRecord(uint256 tableId, bytes32[] key);
```
With Dojo doing ECS, it's a single key instead of an array (the entity).
 `SetField` is just an optimization to support setting partial component value; don't need to use it.

It should be trivial in the new indexer to add a thin apibara layer that ingests the equivalent Dojo event. 

I know this is not exactly what this issue proposes, but maybe it would be even easier to do it at the indexer level instead of at the API level. We plan to support more powerful queries (not all of SQL but a subset in a specific DSL that can easily be turned into incremental queries for streaming).
